[package]
name = "discovery-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
hmac = "0.12"
sha2 = "0.10"
byteorder = "1"
local-ip-address = "0.5"
